### PR TITLE
Merge pull request #1 from Harvard-ATG/master

### PR DESCRIPTION
**Pull request by xueharry**
@arthurian 
I fixed the row split bug, so my tables should work in all 3 browsers now. Let me know if this is ready to send to TLT. 

Thanks,
Harry

### CODE REVIEW

**Comment by xueharry** [comment]
The fix to the table split bug can be found in index.html as well as styles.css. I also did some minor cleanup with my requirements files.

**Comment by arthurian** [comment]
@xueharry :+1: I think it's ready to send to TLT.

**Comment by arthurian** [comment]
@bermudezjd @cmurtaugh @ekiczek Can you review the app and let us know if there's anything else that needs to be done to make it deployable?

**Comment by bermudezjd** [comment]
@arthurian @xueharry I think the best way for us to review this and the course info tool would be to use github's `blame` feature and make any necessary comments in the settings files inline. That way we can catch anything that may have been already merged between the projects. So, I'd say go ahead and merge this in and we'll make any inline comments as needed on the set of commits.

**Pull request merged**
