### PR TITLE
Python 2 to 2/3 and django 1.11 LTS to 2.2 LTS upgrade

### PR DESCRIPTION
**Pull request by joshuagetega**
This PR introduces the following changes:

- Python 2/3 compatibility
- Django 1.11 LTS to 2.2 LTS upgrade

It will be ready for review as soon as the [django-app-lti PR](https://github.com/Harvard-ATG/django-app-lti/pull/3) is reviewed and merged. [Travis CI is failing](https://travis-ci.org/github/Harvard-ATG/canvas_syllabus_export/builds/733395759) specifically because django-app-lti is not updated to django 2 (yet).

Associated JIRA story: [ATGU-2035](https://jira.huit.harvard.edu/browse/ATGU-2035).

### CODE REVIEW

**Comment by joshuagetega** [comment]
I am just seeing, after the fact, in the [story description](https://jira.huit.harvard.edu/browse/ATGU-2035) that the dependency on django-app-lti can be done away with. Now that django-app-lti is updated, I wonder whether it is worthwhile to keep it around. Is there any other app using it? Happy to do away with it if that's the better order of business. Thoughts?

**Review by arthurian — APPROVED** [review]
Looks good @joshuagetega :+1:.

I think the only reason to keep `django-app-lti` (at this point) is for the XML config that's automatically generated. Otherwise, you'd have to add that to the django app, which wouldn't be hard. Since you've already updated that dependency, no need to do that in this PR (maybe a subsequent PR to remove it).

**Review by dodget — APPROVED** [review]
Looks good @joshuagetega !

**Comment by joshuagetega** [comment]
@arthurian @dodget, I have updated the PR with the following changes:

- Added instructions to the README for setting up a virtual environment and running the project locally.

- Removed the [django-app-lti](https://github.com/Harvard-ATG/django-app-lti) and [django-auth-lti](https://github.com/Harvard-University-iCommons/django-auth-lti) dependencies. Instead, the project now uses the [django-lti-provider](https://github.com/ccnmtl/django-lti-provider) package for LTI launch verification. It implements its own Django view for LTI XML config generation. (The django-lti-provider package does have an implementation for XML generation, but some XML fields were not getting generated, hence the implementation within the app). The url and view modules have been updated accordingly.

- Refactored the settings modules by setting up a base.py module that other environment-specific settings modules extend. This is to minimize config redundancy.

Please give the file changes an overview. I have tested the app locally and it works without any problems. In addition, all the unit tests pass. @arthurian, does [this tlt-ops PR](https://github.com/Harvard-University-iCommons/tlt-ops/pull/303/files#diff-fa23e77664ff45c4135d0e95ca7bd597289b6005414dd06e103e2a4fc0d58478) update tlt-ops dev, prod, or both? I would like to go ahead and test this in tlt-dev and then tlt-prod.

**Comment by dodget** [comment]
@joshuagetega - this looks good, but I have some ideas around refactoring which may be out of scope for this PR.

I think we can temporarily use [our fork/branch](https://github.com/Harvard-ATG/django-lti-provider/tree/change/master/course-navigation-dict) of `django-lti-provider` (until 0.4.1 is released which is pending), and it should allow us to factor out the views which generate xml in this project.

If you change the lti configuration to something like this, it should generate the xml that we need
```py
LTI_TOOL_CONFIGURATION = {
    'title': 'Syllabus Export',
    'description': 'Exports course syllabus as html, with additional option of generating a PDF',
    'launch_url': 'syllabuspdf:process_lti_launch_request',
    'landing_url': '/',
    'privacy_level': 'Public',
    'course_navigation': {
        "default": "enabled",
        "enabled": "true",
        "visibility": "admins",
        "text": "Syllabus Export",
    },
}
```

Just my two cents for maintainability 😄 . This could be a follow up story that I'm happy to take on!

**Comment by arthurian** [comment]
@joshuagetega Sorry for the delay getting back to this PR. The changes look good :+1:.

To answer your question about testing in DEV/PROD, the PR you referenced applies to all environments. To test, you'll want to checkout that ops branch locally and then run the `ansible-playbook` command to deploy the code. It might be necessary to remove the existing virtualenv for that project before the deploy to avoid any problems with the python2 virtualenv. I'm happy to give you a quick outline of the steps offline, just let me know.

I agree with @dodget on using our fork/branch of `django-lti-provider` for the sake of maintainability. I think the hope is that the changes in our fork will be contributed back upstream, so we would only need to update the requirement in the future. But this could be a simple follow-up PR to this one so that we can wrap up this story and get it out to production as-is.

**Comment by joshuagetega** [comment]
Thanks for the reviews. I have added [ATGU-2710](https://jira.huit.harvard.edu/browse/ATGU-2710) through which I will implement the use of our fork of the django-lti-provider package for xml generation.

**Pull request merged**
